### ISSUE TITLE
Data too long for column 'MACOUI' at row 1

### ISSUE THREAD

**Issue by BruceHowells** [cjnaz/routermonitor#1]
Apparently, I have longer MACOUI fields than your test data.  I had to change db_fields to end MACOUI VARCHAR(90) just as an arbitrary large number in order to populate my database without crashing out on data to long.

Not sure if VARCHAR(MAX) is that bad an idea in a database which will have a finite number of entries (in almost all cases) and not need to worry too much about query performance.  I did quickly try to see if there was any standard for length, but it looks like there really isn't since it's a human-readable field.

Not sure if this is best disposed of in a FAQ, a "hm, that's big enough" or just going for (MAX), but did want to bring it to your attention.

**Comment by BruceHowells** [comment]
For what it's worth, my particular offending value was "TCL King Electrical Appliances (Huizhou) Co., Ltd", but there are plenty of other nice long ones out there that could be problematic.

**Comment by cjnaz** [comment]
Thanks for the feedback Bruce.
I pushed V1.1 with 2 related changes:
- Increased the field/column widths for both the MACOUI and notes columns to 255.
- Added an optional config file var `MACOUI_field_width` for overriding the default 30 char field within the --list-db report.

The difficult part is with both MACOUI and notes being indeterminate width there is no one right answer for fixing the print widths for this report.  You may want to set MACOUI_field_width smaller than your longest one and let a few lines have goofed up in formatting.
